name: Build
on:
  push:
    tags:
      - 'v*.*.*'
env:
  APP: exim4
  DH_ROOT: dossif
jobs:
  Dockerimage:
    runs-on: ubuntu-20.04
    steps:
      - name: Get release version from git tag
        run: echo "VER=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: binary
          path: .
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DH_ROOT }}/${{ env.APP }}:${{ env.VER }}
